### ISSUE TITLE
Class property workaround doesnt work

### ISSUE THREAD

**Issue by tinmarr** [rubatopy/rubato#85]
foo = classmethod(property(get_func(), set_func())) 

when setting foo it actually overrides foo instead of calling set foo. 😭

**Comment by tsedan** [comment]
Just adding more info here to display what we've tested and what we haven't:

This is the issue with our current code:
![image](https://user-images.githubusercontent.com/9787421/161581860-8fe67b7f-6ce9-404d-a6db-5cbe36d67f3c.png)

These are attempts at pythonic fixes that did not work.
![image](https://user-images.githubusercontent.com/9787421/161581894-a842adf2-9812-4a11-96d4-42e275b408b5.png)
![image](https://user-images.githubusercontent.com/9787421/161582013-4fd777b4-7b94-470a-ad27-7da100662d8f.png)

We may have to go back to the old StaticClass metaclass workaround, but it isn't ideal since the documentation process becomes very manual and breadcrumbing is not ideal.
